spring:
  application:
    name: doctor-service
  data:
    mongodb:
      database: doctor
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#  security:
#    oauth2:
#      resourceserver:
#        opaquetoken:
#          client-secret: id
#          client-id: sec
#          introspection-uri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  port: 8031


logging:
  level:
    root: INFO
    com.innova: DEBUG

