eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

spring:
  data:
    mongodb:
      host: mongo
      database: patient
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: ERROR
    com.innova: DEBUG

