eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  data:
    mongodb:
      database: authentication
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#  security:
#    oauth2:
#      resourceserver:
#        opaquetoken:
#          client-id: 689062928154-pogk4e8v44f7lhl89pon5t8m3cd2hgel.apps.googleusercontent.com
#          client-secret: 9spkQdl0AawztpxoEYA7yEJu
#          introspection-uri: https://www.googleapis.com/oauth2/v3/userinfo


logging:
  level:
    root: INFO
    com.innova: DEBUG
